[SETTINGS]
# Config file for FIM. The Python program looks for specific variable names.

# String of the target directory to use
target = "/"

# Use ntfy?
noti = True
server = 192.168.0.69:8080/Administration_Alerts

# Exclude directory (comma seperated)

excludes = /mnt,/home,/tmp,/dev,/proc,/run,/cache,/.cache,/sys/

